package:
  name: superfit
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools
    - pyqt >=5
    - setuptools_scm
    - matplotlib
    - numpy
    - scipy
    - fffs
    - cython
    - docutils
    - openpyxl

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pyqt >=5
    - fffs
    - cython
    - docutils
    - openpyxl

about:
  home: https://github.com/awacha/superfit
  license: 3-clause BSD license
  dev_url: https://github.com/awacha/superfit.git
  license_family: BSD
  license_file: LICENSE
  summary: A curve fitting program
  description: A GUI utility for nonlinear least-squares fitting of various models

app:
  entry: superfit   [linux]
  entry: superfit   [win]
  summary: A GUI utility for nonlinear least-squares fitting of various models to experimental data
  type: desk

